version: '3.8'

services:
  zookeeper:
    # 这个 tag 实际存在于 Docker Hub
    image: confluentinc/cp-zookeeper:7.4.0-2-ubi8  # :contentReference[oaicite:0]{index=0}
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    # 这个 tag 在 Docker Hub 上可用
    image: confluentinc/cp-kafka:7.4.0            # :contentReference[oaicite:1]{index=1}
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
