jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notes_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1057555034
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS512
logging:
  level:
    org.springframework.security: DEBUG

